server:
  # Render에서 PORT라는 환경변수를 던져줌. 없으면 8080으로 실행
  port: ${PORT:8080}

spring:
  datasource:
    # 1순위: Render에서 넣어줄 SPRING_DATASOURCE_URL
    # 2순위: (선택) 로컬 Postgres 돌릴 때 쓸 기본값
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d4b96qre5dus73eghudg-a:5432/kakaoboard_q87f}
    username: ${SPRING_DATASOURCE_USERNAME:lee}
    password: ${SPRING_DATASOURCE_PASSWORD:hgVP2BUBVI9lYHh4mtZpqe1gRErB1dRH}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.naver.com
    port: 587
    username: mz7701@naver.com
    password: 5J9QSR7UHLEU
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# ✅ 이메일 발신 주소 (EmailService 에서 사용하는 경로)
app:
  email:
    from: ${EMAIL_FROM:mz7701@naver.com}   # 네가 실제로 쓰고 싶은 발신 이메일

# ✅ SendGrid API 키 (EmailService 에서 사용하는 경로)
sendgrid:
  api:
    key: ${SENDGRID_API_KEY:dummy}
