server:
  # Railway에서 PORT 환경변수를 던져줌. 없으면 8080으로 실행
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: WAndZdRtcMKmipHHTUJDRrmqtnAOsNAX
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.naver.com
    port: 587
    username: ${NAVER_MAIL_ID:mz7701@naver.com}
    password: ${NAVER_MAIL_PW:5J9QSR7UHLEU}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


email:
  from: ${EMAIL_FROM:${NAVER_MAIL_ID:mz7701@naver.com}}

# 이름은 sendgrid지만, 실제로는 Brevo/다른 서비스 써도 상관 없음. 그냥 더미값.
sendgrid:
  api-key: ${SENDGRID_API_KEY:dummy}
