server:
  # Railway 내부에서 8080으로 듣게 고정
  port: 8080

spring:
  datasource:
    # ✅ 캡처에 있던 DATABASE_URL 기준으로 그대로 하드코딩
    # postgresql://postgres:비번@postgres.railway.internal:5432/railway
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: WAndZdRtcMKmipHHTUJDRrmqtnAOsNAX
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 필요에 따라 validate / none 등으로 나중에 바꿀 수 있음
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.naver.com
    port: 465           # ✅ 587 → 465
    username: mz7701@naver.com
    password: 5J9QSR7UHLEU
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true     # ✅ SSL 직접 사용
          starttls:
            enable: false    # ✅ 465 쓸 땐 보통 STARTTLS 끔

email:
  from: mz7701@naver.com

# 그냥 더미 값 (실제로 안 써도 됨)
sendgrid:
  api-key: dummy
