server:
  # Render에서 PORT라는 환경변수를 던져줌. 없으면 8080으로 실행
  port: ${PORT:8080}

spring:
  datasource:
    # 1순위: Render에서 넣어줄 SPRING_DATASOURCE_URL
    # 2순위: (선택) 로컬 Postgres 돌릴 때 쓸 기본값
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d4b96qre5dus73eghudg-a:5432/kakaoboard_q87f}
    username: ${SPRING_DATASOURCE_USERNAME:lee}
    password: ${SPRING_DATASOURCE_PASSWORD:hgVP2BUBVI9lYHh4mtZpqe1gRErB1dRH}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.naver.com
    port: 587
    username: mz7701@naver.com
    password: 5J9QSR7UHLEU
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# ✅ 이메일 발신 주소 (Render 환경변수 EMAIL_FROM 에서 읽음)
email:
  from: ${EMAIL_FROM:your-email@example.com}

# ✅ SendGrid API 키 (Render 환경변수 SENDGRID_API_KEY 에서 읽음)
sendgrid:
  api-key: ${SENDGRID_API_KEY:dummy}