spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kakaoboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: xkqtop12

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  mail:
    host: smtp.naver.com
    port: 587                      # ✅ TLS 포트
    username: mz7701@naver.com     # ✅ 네이버 전체 이메일 주소
    password: 5J9QSR7UHLEU  # ✅ 방금 발급받은 애플리케이션 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true           # ✅ TLS 활성화
